name: Destroy API Infra

on:
  workflow_dispatch:

jobs:
  destroy-api-infra:
    name: Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      #Terraform execution
      - name: Terraform Init
        run: |
          cd terraform
          terraform init -reconfigure

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          TF_VAR_ecr_image: ${{ env.ECR_IMAGE }}
          TF_VAR_execution_role_ecs: ${{ secrets.ECS_EXECUTION_ROLE }}
          TF_VAR_vpc_id: ${{ vars.VPC_ID }}
          TF_VAR_subnet_a: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b: ${{ vars.SUBNET_B }}
          TF_VAR_ecs_cluster: ${{ vars.ECS_CLUSTER }}
          TF_VAR_sg_cluster_ecs: ${{ vars.SG_CLUSTER_ECS }}
          TF_VAR_lb_arn: ${{ secrets.LB_ARN }}
          TF_VAR_alb_fastfood_listener_arn: ${{ secrets.LISTENER_DEFAULT_ARN }}
          TF_VAR_db_url: ${{ secrets.HACKATHON_DB_URL }}
          TF_VAR_sns_arn: ${{ secrets.HACKATHON_SNS_ARN }}